# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/yuukilin"

[social.params]
icon = "brand-github"


#[[social]]
#identifier = "threads"
#name = "Threads"
#url = "https://www.threads.net/@yuukilin22"

#[social.params]
#icon = "threads"
#newtab = true
